---
name: Environment

on: [pull_request]

jobs:
  filesystem:
    runs-on: ubuntu-latest
    steps:
      - name: Where am I?
        run: |-
          pwd
          ls -l

  hardware-info:
    runs-on: ubuntu-latest
    steps:
      - name: Install neofetch
        run: sudo apt-get -y install neofetch
      - run: neofetch

  privileges:
    runs-on: ubuntu-latest
    steps:
      - name: Who am I?
        run: whoami
      - name: What can I do?
        run: sudo -l

  variables:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
