---
name: Environment

on: [pull_request]

jobs:
  context:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

  filesystem:
    runs-on: [self-hosted, uuid-label-that-does-not-exist]
    steps:
      - name: Install tree
        run: sudo apt-get -y install tree
      - name: Where am I?
        run: |-
          pwd
          tree -L 4 --dirsfirst -C "$HOME"

  hardware-info:
    runs-on: ubuntu-latest
    steps:
      - name: Install neofetch
        run: sudo apt-get -y install neofetch
      - run: neofetch

  privileges:
    runs-on: ubuntu-latest
    steps:
      - name: Who am I?
        run: whoami
      - name: What can I do?
        run: sudo -l

  variables:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
