---
name: Hardware Info

on: [pull_request]

jobs:
  screenfetch:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: sudo apt-get -y install screenfetch
      - name: display
        run: screenfetch
