name: Hello world

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      run: echo Hello world ${FIRST_NAME} ${MIDDLE_NAME} ${LAST_NAME}!
      env:
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        last_name: Octocat
