name: Hello world

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      run: echo Hello world ${INPUT_FIRST_NAME} ${INPUT_MIDDLE_NAME} ${INPUT_LAST_NAME}!
      with:
        first_name: Mona
        middle_name: The
        last_name: Octocat
