---
name: Secrets

on: [pull_request]

jobs:
  context:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump secrets context
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$SECRETS_CONTEXT"

  can-we-print:
    runs-on: ubuntu-16.04
    steps:
      - name: Does GITHUB_TOKEN change?
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          printf 'RAW: %s\n' "$GITHUB_TOKEN"
          printf 'SHA: %s\n' "$GITHUB_TOKEN" | shasum
      - name: Mask a direct echo?
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: echo "fake-password-12345"
      - name: Redirect to file and cat
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: |-
          printf 'RAW: %s\n' "$SUPER_SECRET"
          echo "$SUPER_SECRET" > secret-file.txt
          cat secret-file.txt
