---
name: Secrets

on: [pull_request]

jobs:
  context:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump secrets context
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$SECRETS_CONTEXT"
