---
name: What Changed

on:
  pull_request:

jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - run: git remote -v show
      - run: git fetch --all
      - run: -|
        export FORK_POINT=$(git merge-base --fork-point "origin/${GITHUB_BASE_REF}")
        printf 'FORK_POINT: %s\n' "$FORK_POINT"
      - run: git diff-tree --no-commit-id --name-only -r --diff-filter=d "${FORK_POINT}.."
